### ISSUE TITLE
Test new publish script in real environment

### ISSUE THREAD

**Issue by sergeevNick** [eigen-space/helper-scripts#32]
After publish script has been updated we should test that all works fine.

Cases for check:
• if no path passed to script only the root project should be updated and published 
• if we pass several paths to script every project in that path should be updated and published
• If we already have package with same version in npm script should exits with error
• no cycle pushes

Also check default value of private in package.json
!**Important**: check for all types of branches master-dev-feature

**Comment by derlagg** [comment]
Checked
