### ISSUE TITLE
Remove scripts that duplicate nodejs api

### ISSUE THREAD

**Issue by tohasan** [eigen-space/helper-scripts#57]
Nodejs API has its own native implementation of `copy`:

* [copyFileSync](https://nodejs.org/docs/latest-v16.x/api/fs.html#fscopyfilesyncsrc-dest-mode)
* [cpSync](https://nodejs.org/docs/latest-v16.x/api/fs.html#fscpsyncsrc-dest-options)
* [rmDirSync](https://nodejs.org/docs/latest-v16.x/api/fs.html#fsrmdirsyncpath-options)
* [mkDirSync](https://nodejs.org/docs/latest-v16.x/api/fs.html#fsmkdirsyncpath-options)

An example of copying a directory recursively:

```
const fs = require('fs');

const [, , src, target] = process.argv;
fs.cpSync(src, target, { recursive: true });
```

**Comment by derlagg** [comment]
Probably, `fs.rmSync(path[, options])` is better alternative then `rmDirSync` because `recursive` was deprecated according to the doc

**Comment by derlagg** [comment]
Probably, `fs.rmSync(path[, options])` is better alternative then `rmDirSync` because `recursive` was deprecated according to the doc
